# Setup
title: Dutch Data Dude
email: jeroen@dutchdatadude.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal blog of Jeroen ter Heerdt, Program Manager at Microsoft in Redmond.
twitter_username: jeroenterheerdt
github_username:  jeroenterheerdt
tagline:             'Data Nerdiness'
url:                 http://www.dutchdatadude.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeroen ter Heerdt
  url:               https://twitter.com/jeroenterheerdt
  email:             jeroen@dutchdatadude.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Code syntax highlighting:
markdown: kramdown
highlighter: rouge

# Disqus comments:
disqus:
  shortname: dutchdatadude

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true   # change to false to default to comments off site-wide